//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcLibrary.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string Subject { get; set; }
        public string MessageText { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SendingMember { get; set; }
        public string ReceivingMember { get; set; }
    }
}
